// ================================================================
// data.js — Firestore CRUD 단일 진입점
//
// 절대규칙:
//   - Firestore API 직접 호출 금지. 이 파일의 export 함수만 사용.
//   - raw_messages는 절대 삭제 금지 (재처리용). 상태만 변경.
// ================================================================

import {
  getCurrentUser,
  getUid,
  initFirebase,
  onAuthChange,
  signIn,
  signOut,
} from './data/core/firebase.js';
import {
  REIMBURSEMENT_CATEGORY_NAME,
  UNCATEGORIZED_CATEGORY_NAME,
} from './data/constants.js';
import {
  deleteAccount,
  deleteCategory,
  deleteCategorySubcategory,
  getAccountById,
  getAccounts,
  getCategories,
  getCategoryById,
  getCategoryByName,
  loadAccounts as _loadAccounts,
  loadCategories as _loadCategories,
  saveAccount,
  saveCategory,
  saveCategoryAutoManaged,
  saveCategoryBudgetRhythm,
  saveCategoryMonthlyTarget,
  saveCategorySubcategory,
} from './data/repositories/master-data.js';
import {
  aggregateByCategory,
  aggregateMonthlyTotals,
  applyReceiptToTransaction,
  applySharedPayment,
  deleteRewardPointEntry,
  deleteSharedPaymentRule,
  deleteTransaction,
  displayCategoryName,
  findSimilarTransaction,
  getReceipt,
  getTransaction,
  isBudgetExcluded,
  isFundCovered,
  isNaverPayTopup,
  isReimbursementExpected,
  linkRawMessageToTransaction,
  listPendingRawMessages,
  listRewardPointEntries,
  listSettlements,
  listSharedPaymentRules,
  listTransactions,
  listUnmatchedReceipts,
  markRawMessageSkipped,
  needsPaymentRailReview,
  saveReceipt,
  saveRewardPointEntry,
  saveSettlement,
  saveSharedPaymentRule,
  saveTransaction,
  updateReceipt,
  updateTransaction,
} from './data/repositories/transactions.js';
import { getAppSettings, saveAppSettings } from './data/repositories/settings.js';
import {
  deactivateProvisionFund,
  deleteBudgetAdjustment,
  getActiveProvisionFunds,
  getProvisionFundById,
  getProvisionFunds,
  listBudgetAdjustments,
  listFundDrawTransactions,
  loadProvisionFunds as _loadProvisionFunds,
  saveBudgetAdjustment,
  saveProvisionFund,
} from './data/repositories/funds.js';
import {
  deleteFinanceActual,
  deleteFinanceAssetTrack,
  deleteFinanceBenchmark,
  deleteFinancePlan,
  listFinanceActuals,
  listFinanceAssetTracks,
  listFinanceBenchmarks,
  listFinanceGoals,
  listFinancePlans,
  listFinanceSnapshots,
  saveFinanceActual,
  saveFinanceAssetTrack,
  saveFinanceBenchmark,
  saveFinanceGoal,
  saveFinancePlan,
  saveFinanceSnapshot,
} from './data/repositories/finance.js';
import {
  deleteWineBottle,
  deleteWineTasting,
  getWineBottle,
  listWineBottles,
  listWineTastings,
  saveWineBottle,
  saveWineTasting,
} from './data/repositories/wine.js';
export {
  REIMBURSEMENT_CATEGORY_NAME,
  UNCATEGORIZED_CATEGORY_NAME,
  aggregateByCategory,
  aggregateMonthlyTotals,
  applyReceiptToTransaction,
  applySharedPayment,
  deactivateProvisionFund,
  deleteAccount,
  deleteBudgetAdjustment,
  deleteCategory,
  deleteCategorySubcategory,
  deleteFinanceActual,
  deleteFinanceAssetTrack,
  deleteFinanceBenchmark,
  deleteFinancePlan,
  deleteRewardPointEntry,
  deleteSharedPaymentRule,
  deleteTransaction,
  deleteWineBottle,
  deleteWineTasting,
  displayCategoryName,
  findSimilarTransaction,
  getAccountById,
  getAccounts,
  getActiveProvisionFunds,
  getAppSettings,
  getCategories,
  getCategoryById,
  getCategoryByName,
  getProvisionFundById,
  getProvisionFunds,
  getReceipt,
  getTransaction,
  getWineBottle,
  isBudgetExcluded,
  isFundCovered,
  isNaverPayTopup,
  isReimbursementExpected,
  linkRawMessageToTransaction,
  listBudgetAdjustments,
  listFinanceActuals,
  listFinanceAssetTracks,
  listFinanceBenchmarks,
  listFinanceGoals,
  listFinancePlans,
  listFinanceSnapshots,
  listFundDrawTransactions,
  listPendingRawMessages,
  listRewardPointEntries,
  listSettlements,
  listSharedPaymentRules,
  listTransactions,
  listUnmatchedReceipts,
  listWineBottles,
  listWineTastings,
  markRawMessageSkipped,
  needsPaymentRailReview,
  saveAccount,
  saveAppSettings,
  saveBudgetAdjustment,
  saveCategory,
  saveCategoryAutoManaged,
  saveCategoryBudgetRhythm,
  saveCategoryMonthlyTarget,
  saveCategorySubcategory,
  saveFinanceActual,
  saveFinanceAssetTrack,
  saveFinanceBenchmark,
  saveFinanceGoal,
  saveFinancePlan,
  saveFinanceSnapshot,
  saveProvisionFund,
  saveReceipt,
  saveRewardPointEntry,
  saveSettlement,
  saveSharedPaymentRule,
  saveTransaction,
  saveWineBottle,
  saveWineTasting,
  updateReceipt,
  updateTransaction,
};

// ================================================================
// 초기화 + 인증
// ================================================================
export async function initData() {
  await initFirebase(async (user) => {
    if (user) await Promise.all([_loadAccounts(), _loadCategories(), _loadProvisionFunds()]);
  });
}

export { getCurrentUser, getUid, onAuthChange, signIn, signOut };
