// ================================================================
// data.js — Firestore CRUD 단일 진입점
//
// 절대규칙:
//   - Firestore API 직접 호출 금지. 이 파일의 export 함수만 사용.
//   - raw_messages는 절대 삭제 금지 (재처리용). 상태만 변경.
// ================================================================

import {
  getCurrentUser,
  getUid,
  initFirebase,
  onAuthChange,
  signIn,
  signOut,
} from './data/core/firebase.js';
import {
  DEV_IDEA_STATUS,
  REIMBURSEMENT_CATEGORY_NAME,
  UNCATEGORIZED_CATEGORY_NAME,
} from './data/constants.js';
import {
  deleteAccount,
  deleteCategory,
  deleteCategorySubcategory,
  getAccountById,
  getAccounts,
  getCategories,
  getCategoryById,
  getCategoryByName,
  loadAccounts as _loadAccounts,
  loadCategories as _loadCategories,
  saveAccount,
  saveCategory,
  saveCategoryBudgetRhythm,
  saveCategoryMonthlyTarget,
  saveCategorySubcategory,
} from './data/repositories/master-data.js';
import {
  aggregateByCategory,
  aggregateMonthlyTotals,
  applyReceiptToTransaction,
  applySharedPayment,
  deleteRewardPointEntry,
  deleteSharedPaymentRule,
  deleteTransaction,
  displayCategoryName,
  findSimilarTransaction,
  getReceipt,
  getTransaction,
  isBudgetExcluded,
  isNaverPayTopup,
  isReimbursementExpected,
  linkRawMessageToTransaction,
  listPendingRawMessages,
  listRewardPointEntries,
  listSettlements,
  listSharedPaymentRules,
  listTransactions,
  listUnmatchedReceipts,
  markRawMessageSkipped,
  needsPaymentRailReview,
  saveReceipt,
  saveRewardPointEntry,
  saveSettlement,
  saveSharedPaymentRule,
  saveTransaction,
  updateReceipt,
  updateTransaction,
} from './data/repositories/transactions.js?v=20260712-domain-rules';
import {
  deleteDevIdea,
  deleteMindbankEntry,
  deletePact,
  getUrge,
  listDevIdeas,
  listMindbankEntries,
  listPacts,
  listUrges,
  saveDevIdea,
  saveMindbankEntry,
  savePact,
  saveUrge,
  updateDevIdea,
  updatePact,
  updateUrge,
} from './data/repositories/behavior.js';
import { getAppSettings, saveAppSettings } from './data/repositories/settings.js?v=20260712-settings-date';
import {
  deleteFinanceActual,
  deleteFinanceAssetTrack,
  deleteFinanceBenchmark,
  deleteFinancePlan,
  listFinanceActuals,
  listFinanceAssetTracks,
  listFinanceBenchmarks,
  listFinanceGoals,
  listFinancePlans,
  listFinanceSnapshots,
  saveFinanceActual,
  saveFinanceAssetTrack,
  saveFinanceBenchmark,
  saveFinanceGoal,
  saveFinancePlan,
  saveFinanceSnapshot,
} from './data/repositories/finance.js';
import {
  getNewsfeedDigestSnapshot,
  getTelegramPublicFeedStatus,
  listNewsfeedItems,
} from './data/repositories/newsfeed.js';
import {
  deleteWineBottle,
  deleteWineTasting,
  getWineBottle,
  listWineBottles,
  listWineTastings,
  saveWineBottle,
  saveWineTasting,
} from './data/repositories/wine.js';

export {
  DEV_IDEA_STATUS,
  REIMBURSEMENT_CATEGORY_NAME,
  UNCATEGORIZED_CATEGORY_NAME,
  aggregateByCategory,
  aggregateMonthlyTotals,
  applyReceiptToTransaction,
  applySharedPayment,
  deleteAccount,
  deleteCategory,
  deleteCategorySubcategory,
  deleteDevIdea,
  deleteFinanceActual,
  deleteFinanceAssetTrack,
  deleteFinanceBenchmark,
  deleteFinancePlan,
  deleteMindbankEntry,
  deletePact,
  deleteRewardPointEntry,
  deleteSharedPaymentRule,
  deleteTransaction,
  deleteWineBottle,
  deleteWineTasting,
  displayCategoryName,
  findSimilarTransaction,
  getAccountById,
  getAccounts,
  getAppSettings,
  getCategories,
  getCategoryById,
  getCategoryByName,
  getNewsfeedDigestSnapshot,
  getReceipt,
  getTelegramPublicFeedStatus,
  getTransaction,
  getUrge,
  getWineBottle,
  isBudgetExcluded,
  isNaverPayTopup,
  isReimbursementExpected,
  linkRawMessageToTransaction,
  listDevIdeas,
  listFinanceActuals,
  listFinanceAssetTracks,
  listFinanceBenchmarks,
  listFinanceGoals,
  listFinancePlans,
  listFinanceSnapshots,
  listMindbankEntries,
  listNewsfeedItems,
  listPacts,
  listPendingRawMessages,
  listRewardPointEntries,
  listSettlements,
  listSharedPaymentRules,
  listTransactions,
  listUnmatchedReceipts,
  listUrges,
  listWineBottles,
  listWineTastings,
  markRawMessageSkipped,
  needsPaymentRailReview,
  saveAccount,
  saveAppSettings,
  saveCategory,
  saveCategoryBudgetRhythm,
  saveCategoryMonthlyTarget,
  saveCategorySubcategory,
  saveDevIdea,
  saveFinanceActual,
  saveFinanceAssetTrack,
  saveFinanceBenchmark,
  saveFinanceGoal,
  saveFinancePlan,
  saveFinanceSnapshot,
  saveMindbankEntry,
  savePact,
  saveReceipt,
  saveRewardPointEntry,
  saveSettlement,
  saveSharedPaymentRule,
  saveTransaction,
  saveUrge,
  saveWineBottle,
  saveWineTasting,
  updateDevIdea,
  updatePact,
  updateReceipt,
  updateTransaction,
  updateUrge,
};

// ================================================================
// 초기화 + 인증
// ================================================================
export async function initData() {
  await initFirebase(async (user) => {
    if (user) await Promise.all([_loadAccounts(), _loadCategories()]);
  });
}

export { getCurrentUser, getUid, onAuthChange, signIn, signOut };
