export const financeState = {
  editScenarioId: null,
  editActualId: null,
  actualSheetOpen: false,
  expandedActualId: null,
  scenarioManagerOpen: false,
  assetOpsOpen: false,
  editAssetTrackId: null,
  assetTrackMenuId: null,
  trackRenameId: null,
  chartTooltip: null,
  compareScenarioId: null,
  editHoldingTrackId: null,
  editHoldingIndex: null,
  moveHoldingTrackId: null,
  moveHoldingIndex: null,
  assetImport: null,
  activeGoalId: null,
  activeGoalName: '',
  targetScenarioId: null,
  scenarios: [],
  assetTracks: [],
  panel: 'scenario',
};

export function resetFinanceTransientState() {
  Object.assign(financeState, {
    editScenarioId: null,
    editActualId: null,
    actualSheetOpen: false,
    expandedActualId: null,
      scenarioManagerOpen: false,
    assetOpsOpen: false,
    editAssetTrackId: null,
    assetTrackMenuId: null,
    trackRenameId: null,
    chartTooltip: null,
    compareScenarioId: null,
    editHoldingTrackId: null,
    editHoldingIndex: null,
    moveHoldingTrackId: null,
    moveHoldingIndex: null,
    assetImport: null,
    panel: 'scenario',
  });
}
